// Popular terminal theme presets
const THEME_PRESETS = {
    dracula: {
        name: "Dracula",
        colors: {
            black: "#21222c",
            red: "#ff5555",
            green: "#50fa7b",
            yellow: "#f1fa8c",
            blue: "#bd93f9",
            magenta: "#ff79c6",
            cyan: "#8be9fd",
            white: "#f8f8f2",
            brightBlack: "#6272a4",
            brightRed: "#ff6e6e",
            brightGreen: "#69ff94",
            brightYellow: "#ffffa5",
            brightBlue: "#d6acff",
            brightMagenta: "#ff92df",
            brightCyan: "#a4ffff",
            brightWhite: "#ffffff",
            background: "#282a36",
            foreground: "#f8f8f2",
            cursor: "#f8f8f2"
        }
    },
    monokai: {
        name: "Monokai",
        colors: {
            black: "#272822",
            red: "#f92672",
            green: "#a6e22e",
            yellow: "#f4bf75",
            blue: "#66d9ef",
            magenta: "#ae81ff",
            cyan: "#a1efe4",
            white: "#f8f8f2",
            brightBlack: "#75715e",
            brightRed: "#f92672",
            brightGreen: "#a6e22e",
            brightYellow: "#f4bf75",
            brightBlue: "#66d9ef",
            brightMagenta: "#ae81ff",
            brightCyan: "#a1efe4",
            brightWhite: "#f9f8f5",
            background: "#272822",
            foreground: "#f8f8f2",
            cursor: "#f8f8f0"
        }
    },
    nord: {
        name: "Nord",
        colors: {
            black: "#3b4252",
            red: "#bf616a",
            green: "#a3be8c",
            yellow: "#ebcb8b",
            blue: "#81a1c1",
            magenta: "#b48ead",
            cyan: "#88c0d0",
            white: "#e5e9f0",
            brightBlack: "#4c566a",
            brightRed: "#bf616a",
            brightGreen: "#a3be8c",
            brightYellow: "#ebcb8b",
            brightBlue: "#81a1c1",
            brightMagenta: "#b48ead",
            brightCyan: "#8fbcbb",
            brightWhite: "#eceff4",
            background: "#2e3440",
            foreground: "#d8dee9",
            cursor: "#d8dee9"
        }
    },
    solarizedDark: {
        name: "Solarized Dark",
        colors: {
            black: "#073642",
            red: "#dc322f",
            green: "#859900",
            yellow: "#b58900",
            blue: "#268bd2",
            magenta: "#d33682",
            cyan: "#2aa198",
            white: "#eee8d5",
            brightBlack: "#002b36",
            brightRed: "#cb4b16",
            brightGreen: "#586e75",
            brightYellow: "#657b83",
            brightBlue: "#839496",
            brightMagenta: "#6c71c4",
            brightCyan: "#93a1a1",
            brightWhite: "#fdf6e3",
            background: "#002b36",
            foreground: "#839496",
            cursor: "#839496"
        }
    },
    solarizedLight: {
        name: "Solarized Light",
        colors: {
            black: "#073642",
            red: "#dc322f",
            green: "#859900",
            yellow: "#b58900",
            blue: "#268bd2",
            magenta: "#d33682",
            cyan: "#2aa198",
            white: "#eee8d5",
            brightBlack: "#002b36",
            brightRed: "#cb4b16",
            brightGreen: "#586e75",
            brightYellow: "#657b83",
            brightBlue: "#839496",
            brightMagenta: "#6c71c4",
            brightCyan: "#93a1a1",
            brightWhite: "#fdf6e3",
            background: "#fdf6e3",
            foreground: "#657b83",
            cursor: "#657b83"
        }
    },
    gruvbox: {
        name: "Gruvbox Dark",
        colors: {
            black: "#282828",
            red: "#cc241d",
            green: "#98971a",
            yellow: "#d79921",
            blue: "#458588",
            magenta: "#b16286",
            cyan: "#689d6a",
            white: "#a89984",
            brightBlack: "#928374",
            brightRed: "#fb4934",
            brightGreen: "#b8bb26",
            brightYellow: "#fabd2f",
            brightBlue: "#83a598",
            brightMagenta: "#d3869b",
            brightCyan: "#8ec07c",
            brightWhite: "#ebdbb2",
            background: "#282828",
            foreground: "#ebdbb2",
            cursor: "#ebdbb2"
        }
    },
    oneDark: {
        name: "One Dark",
        colors: {
            black: "#282c34",
            red: "#e06c75",
            green: "#98c379",
            yellow: "#e5c07b",
            blue: "#61afef",
            magenta: "#c678dd",
            cyan: "#56b6c2",
            white: "#abb2bf",
            brightBlack: "#5c6370",
            brightRed: "#e06c75",
            brightGreen: "#98c379",
            brightYellow: "#e5c07b",
            brightBlue: "#61afef",
            brightMagenta: "#c678dd",
            brightCyan: "#56b6c2",
            brightWhite: "#ffffff",
            background: "#282c34",
            foreground: "#abb2bf",
            cursor: "#abb2bf"
        }
    },
    tomorrowNight: {
        name: "Tomorrow Night",
        colors: {
            black: "#1d1f21",
            red: "#cc6666",
            green: "#b5bd68",
            yellow: "#f0c674",
            blue: "#81a2be",
            magenta: "#b294bb",
            cyan: "#8abeb7",
            white: "#c5c8c6",
            brightBlack: "#969896",
            brightRed: "#cc6666",
            brightGreen: "#b5bd68",
            brightYellow: "#f0c674",
            brightBlue: "#81a2be",
            brightMagenta: "#b294bb",
            brightCyan: "#8abeb7",
            brightWhite: "#ffffff",
            background: "#1d1f21",
            foreground: "#c5c8c6",
            cursor: "#c5c8c6"
        }
    }
};
